name: Deploy Stage

on:
  push:
    branches:
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build CRM (Stage)
        run: npx ng build crm --configuration production --base-href https://safarsystem.demohandler.in/

      - name: Verify Build Output
        run: |
          ls -R dist/crm/browser/

      - name: Deploy CRM to Stage
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 145.79.211.128
          username: u479097380
          password: ${{ secrets.FTP_PASSWORD_STAGE }}
          port: 21
          protocol: ftp
          timeout: 120000
          log-level: verbose
          local-dir: ./dist/crm/browser/
          server-dir: /domains/demohandler.in/public_html/safarsystem/
          dangerous-clean-slate: false
          exclude: |
            **/.htaccess
            api/**
